### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by ozcanoguz** [pato/taboo#1]
Hello,

When you've clicked demo, system gives empty page, can you please check ?

**Comment by pato** [comment]
Can confirm that it is not working, been 7 years since I set it up. I'll give a shot at setting it up again later today, will give an update then

**Comment by ozcanoguz** [comment]
Sorry for disturbing, searching for something that i can translate to Turkish to play with my friends remotely to make these quarantine days easier :)

Thanks for your attention and support.

**Comment by pato** [comment]
So I tried to bring it up using docker compose but didn't have much luck. It's using a very outdated version of core igniter, `2.1.3`, and I don't even remember which version of php/apache/sql it wants. Here is the docker compose I was playing around with if you want to give it a shot

```yaml
version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    image: php:5.5-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: devuser
      PMA_PASSWORD: devpass
    ports:
      - "8080:80"
volumes:
  mysql-data:
```
